language: node_js
node_js:
  - "14"

dist: bionic
addons:
  chrome: stable
  sonarcloud:
    organization: ita-social-projects

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  
  allow_failures:
    - name: check by sonarcloud

  include:
    - stage: build
      script:
      - ng lint
      name: check app by linter
    -
      script:
      - npm run stylelint
      name: check styles by linter
    -
      script:
      - ng test --watch=false --progress=false --codeCoverage=true --browsers=ChromeHeadless
      - ls
      - sonar-scanner -Dsonar.projectKey=ita-social-projects-green-city-client
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.sources=src
        -Dsonar.exclusions=**/node_modules/**
        -Dsonar.tests=src
        -Dsonar.test.inclusions=**/*.spec.ts
        -Dsonar.javascript.lcov.reportPaths=coverage/GreenCityClient/lcov.info
      name: test app & check sonarcloud
    -
      script:
      - ng e2e --protractor-config=e2e/protractor-ci.conf.js
      name: test e2e
    -
      script:      
      - ng build --prod --delete-output-path --base-href=/GreenCityClient/ --outputPath=dist_aot && rm -rf dist_aot
      name: build app using aot compilation
    - stage: deploy
      script: ng build --prod --base-href=/GreenCityClient/ --aot=false --build-optimizer=false
      name: deploy on gh_pages
      if: branch IN (dev, master)
      deploy:
        provider: pages
        github_token: $TRAVIS_GH_TOKEN
        skip_cleanup: true
        local_dir: dist/GreenCityClient
        on:
          branch: dev
   